sudo: true

dist: xenial

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - nvm install --lts
  - nvm use --lts
  - pip install -q tox coverage coveralls tox-travis

script:
  - coverage erase
  - tox

after_success:
  - coverage combine
  - coveralls

before_deploy:
  - git stash --all
  - ./prepare_npm.py
_deploy_provider: &_deploy_provider
  skip_cleanup: true
  on:
    tags: true
    repo: ierror/django-js-reverse
    python: "3.7"
deploy:
  - <<: *_deploy_provider
    provider: pypi
    distributions: sdist bdist_wheel
    user: boerni
    password: "TODO: add password"
  - <<: *_deploy_provider
    provider: npm
    email: mboerni@gmail.com
    api_key: "TODO: add api_key"

cache: pip

notifications:
  email:
    - boerni@gmail.com
