language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy2.7"
  - "pypy3-2"

install:
  - pip install -q tox coverage coveralls tox-travis

script:
  - coverage erase
  - tox

after_success:
  - coverage combine
  - coveralls

notifications:
  email:
    - boerni@gmail.com
